name: 'Build Jupyter Notebooks from Rmd files'
description: 'Automatic conversion of Rmd into Jupyter Notebooks'
inputs:
  directory-name:  # id of input
    description: 'Name of the directory where files should be put'
    required: true
    default: 'notebooks'
  BRANCHE_REF:  # id of input
    description: 'Name of the branch where files should be put'
    required: true
    default: 'master'
    
runs:
  using: "composite"
  steps:
      - name: Convert in ipynb with Jupytext
        run: |
         rm -rf "./temp"
         mkdir -p temp
         pip install jupytext
         cd ./temp
         for i in $(find . -type f \( -iname "*.Rmd" \)); do \
            j="${i%.Rmd}.md" ;
            echo "$j" ;
            if [ -e $j ]
            then
              echo "Converting $j"; \
              #jupytext --to py --execute "$i"
              jupytext --to ipynb "$j" ;
              k="${j%.md}.ipynb" ;
            fi            
         done
         mkdir -p ../${{ inputs.alias }}
         cp -R . ../${{ inputs.alias }}
         cd ..
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: Notebooks
          path: temp/
      - name: Commit new notebooks
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          BRANCHE_REF: ${{ inputs.BRANCHE_REF }}
        run: |
         git config user.name 'github-actions[bot]'
         git config user.email 'github-actions[bot]@users.noreply.github.com'
         # git config user.email github-actions@github.com
         #git checkout ${BRANCHE_REF}
         git status
         git add ${{ inputs.directory-name }}/**/*.ipynb;
         git commit -m "Automated changes";
         git pull
         git push
        shell: bash
