name: Build and Push Notebooks
description: |
  Render Quarto notebooks, organize them, and push to another repository.
inputs:
  destination-repository-name:
    description: Name of the target repo to push notebooks to
    required: true
  echo:
    description: Set to true to pass -M echo:true to quarto render
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Run build_and_push script
      shell: bash
      run: |
        bash "${{ github.action_path }}/scripts/build_and_push.sh" \
          "${{ inputs.destination-repository-name }}" \
          "${{ inputs.echo }}"
    - name: Pushes to another repository
      uses: linogaliana/github-action-push-to-another-repository@main
      with:
        source-directory: 'temp_notebooks/'
        destination-repository-username: 'linogaliana'
        destination-repository-name: '{{ inputs.destination-repository-name }}'
        destination-github-username: 'linogaliana'
        user-email: 'lino.galiana@insee.fr'
        create-target-branch-if-needed: true
        reset-repo: true
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
