name: 'Get artifacts'
description: 'Get artifacts from various locations'
inputs:
  suffix:
    description: 'Suffix for the artifacts'
    required: false
    default: ''
  directory:
    description: 'Path for the artifacts'
    required: false
    default: 'content'
  

runs:
  using: "composite"
  steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: true
#          fetch-depth: 0
#          ref: ${{ github.event.pull_request.head.ref }}
#          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/download-artifact@v2
        with:
          name: md-reste${{ inputs.suffix }}
          path: ./content/course
      - uses: actions/download-artifact@v2
        with:
          name: md-manipulation${{ inputs.suffix }}
          path: ./content/manipulation
      - uses: actions/download-artifact@v2
        with:
          name: md-visualisation${{ inputs.suffix }}
          path: ./content/visualisation
      - uses: actions/download-artifact@v2
        with:
          name: md-modelisation${{ inputs.suffix }}
          path: ./content/modelisation
      - uses: actions/download-artifact@v2
        with:
          name: md-NLP${{ inputs.suffix }}
          path: ./content/NLP
