name: Build and Push Notebooks
description: |
  Render Quarto notebooks, organize them, and push to another repository.
inputs:
  destination-repository-name:
    description: Name of the target repo to push notebooks to
    required: true
  echo:
    description: Set to true to pass -M echo:true to quarto render
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Run build_and_push script
      shell: bash
      env:
        API_INPI_USERNAME: ${{ env.API_INPI_USERNAME }}
        API_INPI_PASSWORD: ${{ env.API_INPI_PASSWORD }}
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        bash "${{ github.action_path }}/scripts/build_and_push.sh" \
          "${{ inputs.destination-repository-name }}" \
          "${{ inputs.echo }}"
